// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtUGGSpVM_vGuIqlhHJEg6ru2i4behCRQ',
    appId: '1:967521357454:web:a71fbbf58182028d1e43df',
    messagingSenderId: '967521357454',
    projectId: 'animeraw-86862',
    authDomain: 'animeraw-86862.firebaseapp.com',
    storageBucket: 'animeraw-86862.firebasestorage.app',
    measurementId: 'G-20E2531EHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPv8BEMuOlBKp5wFNSXhl8CfPYK9F76cI',
    appId: '1:967521357454:android:da44735fd3f099481e43df',
    messagingSenderId: '967521357454',
    projectId: 'animeraw-86862',
    storageBucket: 'animeraw-86862.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz7Qvf9li16ws65b9g7V8G1bGhHfq64kc',
    appId: '1:967521357454:ios:eb9b6c0e96760b221e43df',
    messagingSenderId: '967521357454',
    projectId: 'animeraw-86862',
    storageBucket: 'animeraw-86862.firebasestorage.app',
    iosClientId:
        '967521357454-aejf66lv4mehfe1dvop0d2p2jra84hh2.apps.googleusercontent.com',
    iosBundleId: 'com.izukux2.animehat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz7Qvf9li16ws65b9g7V8G1bGhHfq64kc',
    appId: '1:967521357454:ios:b48475ccb2177b4d1e43df',
    messagingSenderId: '967521357454',
    projectId: 'animeraw-86862',
    storageBucket: 'animeraw-86862.firebasestorage.app',
    iosClientId:
        '967521357454-q4lhfq1fnbla2ds366p6c4dj6gou36b6.apps.googleusercontent.com',
    iosBundleId: 'com.izukux2.animehat.animeHat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtUGGSpVM_vGuIqlhHJEg6ru2i4behCRQ',
    appId: '1:967521357454:web:5b3e2991018ecd681e43df',
    messagingSenderId: '967521357454',
    projectId: 'animeraw-86862',
    authDomain: 'animeraw-86862.firebaseapp.com',
    storageBucket: 'animeraw-86862.firebasestorage.app',
    measurementId: 'G-G58LDHK6BK',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDtUGGSpVM_vGuIqlhHJEg6ru2i4behCRQ',
    appId: '1:967521357454:web:5b3e2991018ecd681e43df',
    messagingSenderId: '967521357454',
    projectId: 'animeraw-86862',
    authDomain: 'animeraw-86862.firebaseapp.com',
    storageBucket: 'animeraw-86862.firebasestorage.app',
    measurementId: 'G-G58LDHK6BK',
  );
}
